@baseUrl = http://localhost:3000/api/v1
@adminToken = change-me

### Create a new consumer
# @name createConsumer
POST {{baseUrl}}/participants
Authorization: Bearer {{adminToken}}

{
  "name": "System Integrator",
  "status": "Enabled"
}

@consumerId = {{createConsumer.response.body.$.id}}

### Create a new consumer token
# @name createConsumerToken
POST {{baseUrl}}/tokens
Authorization: Bearer {{adminToken}}

{
  "name": "System Integrator Token",
  "role": "participant",
  "expireAt": "{{$datetime iso8601 1 y}}",
  "scopeId": "{{consumerId}}"
}

@consumerToken = {{createConsumerToken.response.body.$.value}}

### Create a service group
# @name createServiceGroup
POST {{baseUrl}}/service-groups
Authorization: Bearer {{consumerToken}}

{
    "name": "Project Demo",
    "consumerId": "{{consumerId}}"
}

@serviceGroupId = {{createServiceGroup.response.body.$.id}}

### Create a provider for testing
# @name createProvider
POST {{baseUrl}}/participants
Authorization: Bearer {{adminToken}}

{
    "name": "Demo Service Provider",
    "status": "Enabled"
}

@providerId = {{createProvider.response.body.$.id}}

### Create Data Disk Service Type
# @name createDataDiskServiceType
POST {{baseUrl}}/service-types
Authorization: Bearer {{adminToken}}
Content-Type: application/json

{
    "name": "dummy-data-disk-{{$timestamp}}",
    "propertySchema": {
        "properties": {
            "storage": {
                "type": "integer",
                "label": "Storage (GB)",
                "required": true,
                "validators": [
                    {
                        "type": "enum",
                        "config": {
                            "values": [1, 2, 4, 8, 16, 32, 64, 128, 256, 512, 1024]
                        }
                    }
                ]
            }
        }
    },
    "lifecycleSchema": {
        "states": [
            {"name": "New"},
            {"name": "Created"},
            {"name": "Deleted"}
        ],
        "actions": [
            {
                "name": "create",
                "requestSchemaType": "properties",
                "transitions": [
                    {"from": "New", "to": "Created"}
                ]
            },
            {
                "name": "delete",
                "transitions": [
                    {"from": "Created", "to": "Deleted"}
                ]
            }
        ],
        "initialState": "New",
        "terminalStates": ["Deleted"],
        "runningStates": ["Created"]
    }    
}

### Store the service type id
@dataDiskServiceTypeId = {{createDataDiskServiceType.response.body.$.id}}
@dataDiskServiceTypeName = {{createDataDiskServiceType.response.body.$.name}}

### Create Dummy Data Disk Agent Type
# @name createDummyDataDiskAgentType
POST {{baseUrl}}/agent-types
Authorization: Bearer {{adminToken}}
Content-Type: application/json

{
    "name": "dummy-data-disk-{{$timestamp}}",
    "serviceTypeIds": [
        "{{dataDiskServiceTypeId}}"
    ],
    "configurationSchema": {
        "properties": {
            "mountPath": {
                "type": "string",
                "label": "Mount Path",
                "default": "/mnt/disks"
            }
        }
    }
}

### Store the agent type id
@dummyDataDiskAgentTypeId = {{createDummyDataDiskAgentType.response.body.$.id}}

### Create a new agent with tags
# @name createAgent
POST {{baseUrl}}/agents
Authorization: Bearer {{adminToken}}

{
    "name": "Data Disk Agent",
    "agentTypeId": "{{dummyDataDiskAgentTypeId}}",
    "providerId": "{{providerId}}",
    "tags": ["data-disk-{{$timestamp}}"],
    "configuration": {
        "mountPath": "/mnt/data-disks"
    }
}

@dataDiskAgentId = {{createAgent.response.body.$.id}}

### Create a new data disk service
# @name createDataDiskService
POST {{baseUrl}}/services
Authorization: Bearer {{consumerToken}}

{
    "name": "Data Disk",
    "groupId": "{{serviceGroupId}}",
    "serviceTypeId": "{{dataDiskServiceTypeId}}",
    "properties": {
        "storage": 1
    },
    "agentId": "{{dataDiskAgentId}}"
}

@dataDiskServiceId = {{createDataDiskService.response.body.$.id}}

### Create VM Service Type
# @name createVMServiceType
POST {{baseUrl}}/service-types
Authorization: Bearer {{adminToken}}
Content-Type: application/json

{
    "name": "dummy-vm-{{$timestamp}}",
    "propertySchema": {
        "properties": {
            "cpu": {
                "type": "integer",
                "label": "CPU Cores",
                "required": true,
                "validators": [
                    {
                        "type": "enum",
                        "config": {
                            "values": [1, 2, 4, 8, 16, 32]
                        }
                    }
                ]
            },
            "memory": {
                "type": "integer",
                "label": "Memory (MB)",
                "required": true,
                "validators": [
                    {
                        "type": "enum",
                        "config": {
                            "values": [512, 1024, 2048, 4096, 8192, 16384, 32768, 65536]
                        }
                    }
                ]
            },
            "disk": {
                "type": "integer",
                "label": "Disk (GB)",
                "required": true,
                "validators": [
                    {
                        "type": "enum",
                        "config": {
                            "values": [8, 16, 32, 64, 128, 256, 512, 1024]
                        }
                    }
                ]
            },
            "image": {
                "type": "string",
                "label": "Image",
                "required": true
            },
            

            "dataDisk": {
                "type": "uuid",
                "label": "Data Disk",
                "required": true,
                "validators": [
                    {
                        "type": "serviceReference",
                        "config": {
                            "types": ["{{dataDiskServiceTypeName}}"],
                            "origin": "consumer"
                        }
                    }
                ]
            }
        }
    },
    "lifecycleSchema": {
        "states": [
            {"name": "New"},
            {"name": "Stopped"},
            {"name": "Started"},
            {"name": "Deleted"}
        ],
        "actions": [
            {
                "name": "create",
                "requestSchemaType": "properties",
                "transitions": [
                    {"from": "New", "to": "Stopped"}
                ]
            },
            {
                "name": "start",
                "transitions": [
                    {"from": "Stopped", "to": "Started"},
                    {"from": "Stopped", "to": "Stopped", "onError": true}
                ]
            },
            {
                "name": "stop",
                "transitions": [
                    {"from": "Started", "to": "Stopped"},
                    {"from": "Started", "to": "Started", "onError": true}
                ]
            },
            {
                "name": "update",
                "requestSchemaType": "properties",
                "transitions": [
                    {"from": "Stopped", "to": "Stopped"},
                    {"from": "Started", "to": "Started"}
                ]
            },
            {
                "name": "delete",
                "transitions": [
                    {"from": "Stopped", "to": "Deleted"},
                    {"from": "Started", "to": "Deleted"}
                ]
            }
        ],
        "initialState": "New",
        "terminalStates": ["Deleted"],
        "runningStates": ["Started"]
    }
}

### Store the service type id
@vmServiceTypeId = {{createVMServiceType.response.body.$.id}}

### Create VM CPU Usage Metric Type
# @name createVMCpuUsageMetricType
POST {{baseUrl}}/metric-types
Authorization: Bearer {{adminToken}}
Content-Type: application/json

{
    "name": "vm.cpu.usage",
    "entityType": "Resource"
}

### Create VM Memory Usage Metric Type
# @name createVMMemoryUsageMetricType
POST {{baseUrl}}/metric-types
Authorization: Bearer {{adminToken}}
Content-Type: application/json

{
    "name": "vm.memory.usage",
    "entityType": "Resource"
}


### Create VM Disk Usage Metric Type
# @name createVMDiskUsageMetricType
POST {{baseUrl}}/metric-types
Authorization: Bearer {{adminToken}}
Content-Type: application/json

{
    "name": "vm.disk.usage",
    "entityType": "Resource"
}

### Create VM Network Throughput Metric Type
# @name createVMNetworkThroughputMetricType
POST {{baseUrl}}/metric-types
Authorization: Bearer {{adminToken}}
Content-Type: application/json

{
    "name": "vm.network.throughput",
    "entityType": "Resource"
}

### Create Dummy VM Agent Type
# @name createDummyVMAgentType
POST {{baseUrl}}/agent-types
Authorization: Bearer {{adminToken}}
Content-Type: application/json

{
    "name": "dummy-vm-{{$timestamp}}",
    "serviceTypeIds": [
        "{{vmServiceTypeId}}"
    ],
    "configurationSchema": {
        "properties": {
            "timeout": {
                "type": "integer",
                "label": "Timeout (seconds)",
                "default": 60
            },
            "retries": {
                "type": "integer",
                "label": "Number of Retries",
                "default": 3
            },
            "environment": {
                "type": "string",
                "label": "Environment",
                "default": "production"
            },
            "proxmox": {
                "type": "object",
                "label": "Proxmox Configuration",
                "properties": {
                    "node": {
                        "type": "string",
                        "label": "Proxmox Node"
                    },
                    "storage": {
                        "type": "string",
                        "label": "Storage Name"
                    }
                }
            }
        }
    }
}

### Store the agent type id
@dummyVMAgentTypeId = {{createDummyVMAgentType.response.body.$.id}}

### Create an agent with tags
# @name createAgent
POST {{baseUrl}}/agents
Authorization: Bearer {{adminToken}}

{
    "name": "VM Agent",
    "agentTypeId": "{{dummyVMAgentTypeId}}",
    "providerId": "{{providerId}}",
    "tags": ["gpu-{{$timestamp}}", "high-memory", "ssd-storage"],
    "configuration": {
        "timeout": 45,
        "retries": 2,
        "environment": "test",
        "proxmox": {
            "node": "pve-01",
            "storage": "local-lvm"
        }
    }
}

@agentId = {{createAgent.response.body.$.id}}
@uniqueTag = {{createAgent.response.body.$.tags.[0]}}

### Create a new agent token
# @name createAgentToken
POST {{baseUrl}}/tokens
Authorization: Bearer {{adminToken}}

{
  "name": "Test Agent Token",
  "role": "agent",
  "expireAt": "{{$datetime iso8601 1 y}}",
  "scopeId": "{{agentId}}"
}

@agentToken = {{createAgentToken.response.body.$.value}}

### Get agent's own information via authenticated endpoint
# @name getAgentMe
GET {{baseUrl}}/agents/me
Authorization: Bearer {{agentToken}}

### Create a new service using agent's unique tag for discovery
# @name createService
POST {{baseUrl}}/services
Authorization: Bearer {{consumerToken}}

{
    "name": "Proxmox VM",
    "properties": {
        "cpu": 4,
        "memory": 512,
        "disk": 8,
        "image": "debian-12-amd64",
        "dataDisk": "{{dataDiskServiceId}}"
    },
    "agentTags": ["{{uniqueTag}}"],
    "serviceTypeId": "{{vmServiceTypeId}}",
    "groupId": "{{serviceGroupId}}"
}

@serviceId = {{createService.response.body.$.id}}

### Get a service by ID
GET {{baseUrl}}/services/{{serviceId}}
Authorization: Bearer {{consumerToken}}

### Update name - Should not trigger a job
PATCH {{baseUrl}}/services/{{serviceId}}
Authorization: Bearer {{consumerToken}}

{
    "name": "Proxmox VM - Demo"
}

### Start Service
POST {{baseUrl}}/services/{{serviceId}}/start
Authorization: Bearer {{consumerToken}}

### Get a service by ID
GET {{baseUrl}}/services/{{serviceId}}
Authorization: Bearer {{consumerToken}}

### Hot update vm status
PATCH {{baseUrl}}/services/{{serviceId}}
Authorization: Bearer {{consumerToken}}

{
    "properties": {
        "cpu": 8,
        "memory": 1024
    }
}

### Get a service by ID
GET {{baseUrl}}/services/{{serviceId}}
Authorization: Bearer {{consumerToken}}

### Stop Service
POST {{baseUrl}}/services/{{serviceId}}/stop
Authorization: Bearer {{consumerToken}}

### Get a service by ID
GET {{baseUrl}}/services/{{serviceId}}
Authorization: Bearer {{consumerToken}}

### Cold update vm status
PATCH {{baseUrl}}/services/{{serviceId}}
Authorization: Bearer {{consumerToken}}

{
    "properties": {
        "cpu": 4,
        "memory": 4096
    }
}

### Get a service by ID
GET {{baseUrl}}/services/{{serviceId}}
Authorization: Bearer {{consumerToken}}

### Delete a service
DELETE {{baseUrl}}/services/{{serviceId}}
Authorization: Bearer {{consumerToken}}

### Get a service by ID
GET {{baseUrl}}/services/{{serviceId}}
Authorization: Bearer {{consumerToken}}

### List all services
GET {{baseUrl}}/services
Authorization: Bearer {{consumerToken}}


